spring.application.name=paylink-system
server.port=8080

#Database SQL
spring.datasource.url=${DB_URL_PROD}?preparedStatementCacheQueries=0
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Liquibase Core
spring.liquibase.change-log=classpath:/db/master.changelog.yaml
spring.liquibase.user=${DB_USERNAME_PROD}
spring.liquibase.password=${DB_PASSWORD_PROD}
spring.liquibase.enabled=false

#JWT
auth.core.jwt.access-token-expiry=3600000
auth.core.jwt.refresh-token-expiry=10800000
auth.core.jwt.secret-key=${JWT_SECRET_PROD}

paylink.system.allowed-url=${ALLOWED_URL_PROD}
paylink.system.allowed-method=GET,POST,PUT,PATCH,DELETE,OPTIONS
paylink.system.allowed-public-endpoint=/dashboard/auth/login,/dashboard/auth/register,/paylink/v1/generate

#Server Config
server.tomcat.connection-timeout=10s
server.max-http-request-header-size=8KB
server.tomcat.accept-count=100
server.tomcat.max-connections=10000
server.tomcat.max-http-form-post-size=2MB

# AES Encryption
encryption.aes.key=${AES_KEY_PROD}
encryption.aes.iv=${AES_IV_PROD}

# REDIS
spring.data.redis.host=${REDIS_HOST_PROD}
spring.data.redis.port=${REDIS_PORT_PROD}
spring.data.redis.password=${REDIS_PASSWORD_PROD}
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=45000

# Google Cloud Pub/Sub
spring.cloud.gcp.project-id=ryzen-sys
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=600

paylink.dashboard.auth.client-id-prefix=PMU-001-
paylink.dashboard.auth.shared-key-prefix=SK-
paylink.payment.generate.base-frontend-url=https://paylink.mrifqyz.my.id/payment/v1/

# Signature Verification
paylink.signature.enabled-endpoints=/paylink/v1/generate
paylink.signature.timestamp-tolerance-seconds=300

# Logging
logging.level.net.ryzen.paylinksystem=INFO

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=false
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=false
