# Staging Environment Configuration
spring.application.name=paylink-system
server.port=8080
server.servlet.context-path=/paylink

#Database SQL
spring.datasource.url=${DB_URL_STAGING}?preparedStatementCacheQueries=0
spring.datasource.username=${DB_USERNAME_STAGING}
spring.datasource.password=${DB_PASSWORD_STAGING}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false

#JWT
auth.core.jwt.access-token-expiry=3600000
auth.core.jwt.refresh-token-expiry=10800000
auth.core.jwt.secret-key=${JWT_SECRET_STAGING}

paylink.system.allowed-url=${ALLOWED_URL_STAGING}
paylink.system.allowed-method=GET,POST,PUT,PATCH,DELETE,OPTIONS
paylink.system.allowed-public-endpoint=/dashboard/auth/login,/dashboard/auth/register,/v1/generate,/actuator/health/liveness,/actuator/health/readiness,/actuator/prometheus,/actuator/metrics,/v1/**

#Server Config
server.tomcat.connection-timeout=10s
server.max-http-request-header-size=8KB
server.tomcat.accept-count=100
server.tomcat.max-connections=10000
server.tomcat.max-http-form-post-size=2MB

# AES Encryption
encryption.aes.key=${AES_KEY_STAGING}
encryption.aes.iv=${AES_IV_STAGING}

# REDIS
spring.data.redis.host=${REDIS_HOST_STAGING}
spring.data.redis.port=${REDIS_PORT_STAGING}
spring.data.redis.password=${REDIS_PASSWORD_STAGING}
spring.data.redis.ssl.enabled=false
spring.data.redis.timeout=45000

# Google Cloud Pub/Sub
spring.cloud.gcp.project-id=ryzen-sys
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.pubsub.subscriber.parallel-pull-count=1
spring.cloud.gcp.pubsub.subscriber.max-ack-extension-period=600

paylink.dashboard.auth.client-id-prefix=PMU-001-
paylink.dashboard.auth.shared-key-prefix=SK-
paylink.payment.generate.base-frontend-url=https://paylink-staging.mrifqyz.my.id/payment/v1/

# Signature Verification
paylink.signature.enabled-endpoints=/paylink/v1/generate
paylink.signature.timestamp-tolerance-seconds=300

# Logging
logging.level.net.ryzen.paylinksystem=DEBUG

# Actuator & Prometheus Metrics
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true
management.health.pubsub.enabled=true

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

paylink.pubsub.topic-payment=streaming-payment-data-sub

# Credit Card
paylink.credit-card.callback-url=https://api-staging.mrifqyz.my.id/paylink/v1/credit-card/3ds-callback/{token_id}
paylink.credit-card.frontend-redirect-url-success=https://paylink-staging.mrifqyz.my.id/payment/success
paylink.credit-card.frontend-redirect-url-failed=https://paylink-staging/payment/failed