apiVersion: v1
kind: Secret
metadata:
  name: paylink-system-staging-secret
  namespace: paylink-staging
type: Opaque
stringData:
  DB_URL_STAGING: "${DB_URL_STAGING}"
  DB_USERNAME_STAGING: "${DB_USERNAME_STAGING}"
  DB_PASSWORD_STAGING: "${DB_PASSWORD_STAGING}"
  JWT_SECRET_STAGING: "${JWT_SECRET_STAGING}"
  REDIS_PASSWORD_STAGING: "${REDIS_PASSWORD_STAGING}"
  GCP_CREDENTIALS: "${GCP_CREDENTIALS}"